version: "3.8"
services:
  ibfflood:
    build:
      context: .
    image: ibf-floods-pipeline
    ports:
      - "587:587"
    #env_file:
    #  - secrets
    volumes: 
      - ./pipeline:/home/ibf
    command: run-flood-model