version: "3.8"
services:
  ibfflood:
    build:
      context: .
    image: ibf-floods-pipeline_sn2
    ports:
      - "587:587"
    volumes: 
      - ./pipeline:/home/ibf
    command: run-flood-model