name: run-flood-model2
on: workflow_dispatch
jobs:
  run-flood-model:
    runs-on: ubuntu-latest
    env:
      running-directory: ./pipeline
    if: ${{ github.repository_owner != 'rodekruis' }}
    steps:  
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install system dependencies1
      run: |
       sudo apt-get update
       sudo apt-get install -y \
         software-properties-common \
         build-essential \
         nano \
         vim \
         python3-pip \
         git \
         wget \
         libxml2-utils\
         libproj-dev \
         libgeos-dev \
         libspatialindex-dev \
         libudunits2-dev \
         libspatialindex-dev \
         libssl-dev \
         libgdal-dev \
         libxml2-utils\
         gfortran \
         kmod \
         gfortran \
         apache2
         
    - name: Install system dependencies2
      run: |
       sudo add-apt-repository ppa:ubuntugis/ppa
       sudo apt-get update
       sudo apt-get install -y postgresql postgresql-contrib  
       sudo apt-get install -y libproj-dev libgeos++-dev
       sudo apt-get install -y gdal-bin 
       sudo apt-get install -y libgdal-dev
       sudo apt-get install libgnutls28-dev


         
    - name: Install system dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y \
         libgirepository1.0-dev\
         gcc\
         pkg-config\
         python3-dev\
         gir1.2-gtk-3.0\
  
         
    - name: Install more Python dependencies
      run: |  
        python -m pip install -r requirements.txt
        
    - name: Install script
      run: |
        python -m pip install .
      working-directory: ${{ env.running-directory }}
      
    - name: Run script
      env:
        ADMIN_LOGIN: ${{ secrets.ADMIN_LOGIN }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        GLOFAS_PW: ${{ secrets.GLOFAS_PW }}
        GLOFAS_USER: ${{ secrets.GLOFAS_USER }}
        GOOGLE_DRIVE_DATA_URL: ${{ secrets.GOOGLE_DRIVE_DATA_URL }}
        UGA_URL: ${{ secrets.UGA_URL }}
        ZMB_URL: ${{ secrets.ZMB_URL }}
        ETH_URL: ${{ secrets.ETH_URL }}
        KEN_URL: ${{ secrets.KEN_URL }}
        UGA_PASSWORD: ${{ secrets.UGA_PASSWORD }}
        ZMB_PASSWORD: ${{ secrets.ZMB_PASSWORD }}
        ETH_PASSWORD: ${{ secrets.ETH_PASSWORD }}
        KEN_PASSWORD: ${{ secrets.KEN_PASSWORD }}
      run: |
        run-flood-model
      working-directory: ${{ env.running-directory }}
