name: run-flood-model
on:
  workflow_dispatch
  
jobs:
  run-flood-model:
    runs-on: ubuntu-latest
    env:
      running-directory: ./pipeline
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-eccodes \
          libgirepository1.0-dev\
          libproj-dev \
          libgeos-dev \
          libspatialindex-dev \
          libudunits2-dev \
          libssl-dev \
          libgdal-dev
             
    - name: Install more Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        
    - name: Install script
      run: |
        python -m pip install .
      working-directory: ${{ env.running-directory }}
    - name: Run script
      env:
        IBF_API_URL: ${{ secrets.IBF_API_URL }}
        API_SERVICE_URL: ${{ secrets.API_SERVICE_URL }}
        API_LOGIN_URL: ${{ secrets.API_LOGIN_URL }}
        ADMIN_LOGIN: ${{ secrets.ADMIN_LOGIN }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        GLOFAS_API_KEY: ${{ secrets.GLOFAS_API_KEY }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        GLOFAS_API_URL: ${{ secrets.GLOFAS_API_URL }}
        GLOFAS_PW: ${{ secrets.GLOFAS_PW }}
        GLOFAS_FTP: ${{ secrets.GLOFAS_FTP }}
        GLOFAS_USER: ${{ secrets.GLOFAS_USER }}
        DATALAKE_STORAGE_ACCOUNT_NAME: ${{ secrets.DATALAKE_STORAGE_ACCOUNT_NAME }}
        DATALAKE_STORAGE_ACCOUNT_KEY: ${{ secrets.DATALAKE_STORAGE_ACCOUNT_KEY }}
        DATALAKE_API_VERSION: ${{ secrets.DATALAKE_API_VERSION }}
        GOOGLE_DRIVE_DATA_URL: ${{ secrets.GOOGLE_DRIVE_DATA_URL }}
      run: |
        run-flood-model
      working-directory: ${{ env.running-directory }}
